source "https://rubygems.org"

gem "rails", "~> 5.0.7.1"
gem "pg"
gem "puma"
gem "rails_12factor"
gem "devise"
gem "pundit"
gem "rack-cache"
gem "dalli"
gem "textacular", git: "https://github.com/textacular/textacular.git"
gem "dropbox-sdk", require: "dropbox_sdk"
gem "chartkick"
gem "groupdate"
gem "sass"
gem "bootstrap-sass"
gem "sass-rails"
gem "haml-rails"
gem "uglifier"
gem "autoprefixer-rails"
gem "pry-rails"
gem "marco-polo"
gem "hashie"
gem "pagy"
gem "cacheable_flash"
gem "mustache"
gem "memoist", require: false
gem "bugsnag"
gem "clockwork"
gem "skylight"
gem "timber"
gem "secure_headers"
gem "alexa_verifier", git: "https://github.com/sidoh/alexa_verifier.git"

group :test do
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 3.7.2"
  gem "rspec-mocks"
  gem "simplecov", require: false
  gem "timecop"
end
